name: GIS and dev experiments
baseurl: http://thomasg77.github.io/

permalink: /:year/:month/:day/:title.html

github_name: github.com/ThomasG77
github_url: http://github.com/ThomasG77

twitter_name: ThomasG77
twitter_url: http://twitter.com/ThomasG77

pygments: true
